# Retour sur les notions de variable et d'inférence

R Markdown provides an authoring framework for data science. You can use a single R Markdown file to both


## Retour sur la notion de variable (PHILIPPE ET JÉRÉMY)
Insister sur la définition des variables! Toujours aller lire les sources. Concept de proxy
Garder les variables latentes pour l'ACP. Possibité de la faire JÉRÉMY

## Retour sur la statistique descriptive et la statistique inférentielle (ENCADRÉ)

## La notion de distribution (JÉRÉMY)



## Statistiques descriptives sur des variables continues (PHILIPPE)

### Les paramètres de tendance centrale
### Les paramètres de position
### Les paramètres de dispersion
### Les paramètres de forme
### La transformation des variables

### TEST ET INFÉRENCE
La notion de bootstrap : 
concept de bootstrap et 

### LA NOTION DE VALEUR DE P ou la mettre
mesures sur populations complètes ou Échantillons

### Pour aller plus loin : les statistiques descriptives pondérées

## Statistiques descriptives sur des variables qualitatives
tableau de fréquences
