# La  magie des graphiques

Dans ce chapitre, nous décrirons la notion de variable, permettant l’opérationnalisation d’un concept. Comprendre les différents types de variables est essentiel en statistiques. En effet, en fonction du type de variable à l'étude, les tests d’hypothèses et les méthodes de statistique inférentielle que l’on pourra appliquer seront différents. Nous distinguerons ainsi cinq types de variables : nominale, ordinale, discrète, continue et semi-quantitative. Nous présenterons ensuite les différentes statistiques descriptives univariées qui peuvent s’appliquer à ces types de variables.

https://www.r-bloggers.com/graphics-in-r-with-ggplot2/


## Phisolophie du ggplot2

### Grammaire

### Les types de gémotries

### L'habillage
Les titres et annotations
thèmes préfaits


## Des exemples de graphiques


Histogramme : fréquence et densité et densité2
Ajout de la courbe normale, gamma

Histogram with colored tail

Histogram OR boxplot with colored tail OUTLIERS


Boxplot et violons plots : horizontal et vertical

Nuage de points : ajout linéaire, non linéaire, densité scatterplot

qqplot?

Error bar

Line plot et Geometry ribon

Pointe de tarte, barres empliées

Spyderplot



::: {.bloc_aller_loin .bloc_aller_loin_png data-latex="{blocs/aller_loin}"}
Les cartes
:::

## Les figures à partir de plusieurs graphiques : 

ggarrange

## Les exportations des graphiques


