# La régression linéaire multiple {#chapitre4}

For documents, the basic units are often sections. For presentations, the basic units are slides. A section in the Markdown source document often indicates a new slide in the presentation formats. In this chapter, we introduce the built-in presentation formats in the **rmarkdown** package.

::: {.bloc_objectif .bloc_objectif_png data-latex="{blocs/objectif}"}
Ceci est le simple bloc "objectif"
:::

::: {.bloc_notes .bloc_notes_png data-latex="{blocs/notes}"}
Ceci est le simple bloc "notes"
:::

::: {.bloc_aller_loin .bloc_aller_loin_png data-latex="{blocs/aller_loin}"}
Ceci est le simple bloc "pour aller plus loin"
:::

::: {.bloc_astuce .bloc_astuce_png data-latex="{blocs/astuce}"}
Ceci est le simple bloc "astuce"
:::

::: {.bloc_attention .bloc_attention_png data-latex="{blocs/attention}"}
Ceci est le simple bloc "attention"
:::


À juste titre, Bressoux [-@bressoux2010, pp 15] signale que « la causalité relève d'une interprétation théorique de la relation et celle-ci n'est jamais déterminée par les calculs statistiques ».

démarche théorique.
mécanisme qui explique la causalité.
